spring:
  datasource: # H2 DB 설정
    url: jdbc:h2:mem:finance
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # H2 DB 웹콘솔 사용하도록 설정 (http://localhost:8080/h2-console)
  jpa:
    database: H2
    show-sql: true # Jpa 수행 시 SQL문 로그 출력
    properties:
      hibernate:
        format_sql: true # 쿼리 출력시 포맷 정렬되도록 설정
  profiles:
    active: local
  #thymeleaf 설정
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
    suffix: .html   # 파일 확장자
    cache: false
  #mvc:
    #static-path-pattern: /static/** # spring mvc 정적경로 변경
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  servlet:
    context-path: /chagvv 
  port: 80